name: Deploy Blog

on: 
  push:
    branches:
      - main

jobs:
   install-html:
     runs-on: self-hosted
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: Install Dependecies
         run: pip install pelican
         
       - name: Generate Html
         run : make html

       - name: Deploy on nginx
         run:  cp output/* /home/sameer/app/blog
       
